steps:
- name: 'gcr.io/google.com/cloudsdktool/cloudsdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gsutil -m rsync -d -r learning_airflow/dags gs://us-central1-learning-compos-6c8a22d5-bucket/dags
    gsutil -m rsync -d -r learning_airflow/scripts gs://us-central1-learning-compos-6c8a22d5-bucket/scripts
    gsutil -m rsync -d -r learning_airflow/sql gs://us-central1-learning-compos-6c8a22d5-bucket/sql